# This is a basic workflow to help you get started with Actions

name: Build-Universal-Arterytek-Openocd

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-job:
    # The type of runner that the job will run on
    runs-on: macos-15
    #environment: secrets
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up macports
        run: |
          port version

        #env:
        #  REPO_KEY: ${{ secrets.REPO_KEY }}
