# This is a basic workflow to help you get started with Actions

name: Build-Universal-Arterytek-Openocd

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  macports_version: 2.10.5
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-job:
    # The type of runner that the job will run on
    runs-on: macos-15
    #environment: secrets
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out openocd portfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            data/openocd/ports
      - name: Set up macports
        run: |
          mkdir ${macports}
          cd ${macports}
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-${macports_version}.tar.bz2
          tar xf MacPorts-${macports_version}.tar.bz2
          cd MacPorts-${macports_version}
          ./configure --enable-readline --prefix=$macports --with-no-root-privileges
          make && make install
          echo ${macports}/bin >> $GITHUB_PATH
          export PATH=$PATH:${macports}/bin

          port selfupdate
          portsdir=$GITHUB_WORKSPACE/data/openocd/ports
          portsconf=${macports}/etc/macports/sources.conf
          echo -e "file://$portsdir\n$(cat $portsconf)" > $portsconf
          pushd $portsdir
          portindex
          popd

          port install openocd +universal +stlink
        env:
          macports: ${{ runner.temp }}/macports

      - name: Prepare build artifacts
        run: |
          mkdir -p dist/openocd
          pushd dist/openocd
          mkdir -p bin lib share
          cp ${macports}/bin/openocd bin/
          cp ${macports}/lib/libusb-1.0.0.dylib lib/
          cp -r ${macports}/share/openocd share/
          cd ..
          tar cjf openocd.tar.bz2 openocd
          echo Created archive $(readlink -f openocd.tar.bz2)
          popd
        env:
          macports: ${{ runner.temp }}/macports
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openocd-arterytek-universal
          path: |
            dist/openocd.tar.bz2
            
        #  REPO_KEY: ${{ secrets.REPO_KEY }}
