# This is a basic workflow to help you get started with Actions

name: Build-Universal-Arterytek-Openocd

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-job:
    # The type of runner that the job will run on
    runs-on: macos-15
    #environment: secrets
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up macports
        run: |
          mkdir ~/macports
          cd ~/macports
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-${macports_version}.tar.bz2
          tar xf MacPorts-${macports_version}.tar.bz2
          cd MacPorts-${macports_version}
          ./configure --enable-readline --prefix=$HOME/macports --with-no-root-privileges
          make && make install
          export PATH=$PATH:~/macports/bin

          port version

        env:
          macports_version: 2.10.5
        #  REPO_KEY: ${{ secrets.REPO_KEY }}
